# Generated by Django 3.1.3 on 2020-11-03 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 19, 8, 31, 511590)),
        ),
    ]
