# Generated by Django 3.1.3 on 2020-11-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_auto_20201103_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
